// Builds the hotlist email body — the same table-based layout as GAS
// sendHotlistEmail (Hotlist.js), which renders consistently across email
// clients. Unlike GAS, every value is HTML-escaped, so a "<" or "&" typed
// into a skills field can't break (or inject into) the email.
export type HotlistConsultant = {
  consultantName: string;
  role: string;
  technologySkills: string;
  visaStatus: string;
  relocation: string;
  experience: string;
  location: string;
  availability: string;
};

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const COLUMNS: { label: string; width: string; key: keyof HotlistConsultant }[] = [
  { label: "Name", width: "15%", key: "consultantName" },
  { label: "Role", width: "14%", key: "role" },
  { label: "Skills", width: "18%", key: "technologySkills" },
  { label: "Visa", width: "7%", key: "visaStatus" },
  { label: "Relocation", width: "10%", key: "relocation" },
  { label: "Exp", width: "8%", key: "experience" },
  { label: "Location", width: "12%", key: "location" },
  { label: "Availability", width: "16%", key: "availability" },
];

export function buildHotlistEmailHtml(companyName: string, consultants: HotlistConsultant[], date: Date): string {
  const dateStr = date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "2-digit" });
  const company = escapeHtml(companyName);
  const td = 'style="padding:8px 6px;border:1px solid #e0e0e0;word-wrap:break-word;overflow-wrap:break-word;"';
  const tdBold = 'style="padding:8px 6px;border:1px solid #e0e0e0;word-wrap:break-word;overflow-wrap:break-word;font-weight:600;"';
  const th = 'style="padding:8px 6px;text-align:left;border:1px solid #e0e0e0;font-weight:600;font-size:12px;white-space:nowrap;"';

  const rows = consultants
    .map((c, i) => {
      const cells = COLUMNS.map((col, j) => `<td ${j === 0 ? tdBold : td}>${escapeHtml(c[col.key] ?? "")}</td>`).join("");
      return `<tr style="background:${i % 2 === 0 ? "#ffffff" : "#fafafa"};">${cells}</tr>`;
    })
    .join("");

  return (
    '<table cellpadding="0" cellspacing="0" border="0" width="100%" style="font-family:Arial,Helvetica,sans-serif;max-width:900px;margin:0 auto;">' +
    `<tr><td style="background:#1a237e;color:#ffffff;padding:20px 30px;border-radius:8px 8px 0 0;"><h1 style="margin:0;font-size:22px;">${company}</h1>` +
    '<p style="margin:4px 0 0;font-size:13px;opacity:0.85;">IT Staffing Solutions</p></td></tr>' +
    '<tr><td style="padding:24px 20px;background:#ffffff;border-left:1px solid #e0e0e0;border-right:1px solid #e0e0e0;">' +
    '<h2 style="margin:0 0 4px;font-size:18px;color:#1a237e;">Available Consultants - Hotlist</h2>' +
    `<p style="margin:0 0 16px;font-size:13px;color:#666;">Date: ${dateStr} | ${consultants.length} consultant(s)</p>` +
    '<table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;font-size:12px;table-layout:fixed;">' +
    `<colgroup>${COLUMNS.map((c) => `<col style="width:${c.width};">`).join("")}</colgroup>` +
    `<thead><tr style="background:#f5f5f5;">${COLUMNS.map((c) => `<th ${th}>${c.label}</th>`).join("")}</tr></thead>` +
    `<tbody>${rows}</tbody></table></td></tr>` +
    '<tr><td style="background:#f5f5f5;padding:16px 20px;border-radius:0 0 8px 8px;border:1px solid #e0e0e0;border-top:none;">' +
    `<p style="margin:0;font-size:11px;color:#888;">This hotlist was generated by ${company} on ${dateStr}.</p>` +
    '<p style="margin:4px 0 0;font-size:11px;color:#888;">For inquiries, please reply to this email.</p>' +
    "</td></tr></table>"
  );
}

// Plain-text version for email clients/paste targets that drop HTML.
export function buildHotlistText(companyName: string, consultants: HotlistConsultant[], date: Date): string {
  const dateStr = date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "2-digit" });
  const lines = consultants.map((c) =>
    COLUMNS.map((col) => `${col.label}: ${c[col.key] ?? ""}`).join(" | ")
  );
  return `${companyName} — Available Consultants (Hotlist)\nDate: ${dateStr} | ${consultants.length} consultant(s)\n\n${lines.join("\n")}`;
}
