// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate/studio/db pull) uses this. It's DIRECT_URL, not
    // DATABASE_URL — Supabase's transaction-mode pooler (used by the app at
    // runtime via the pg driver adapter) doesn't support the DDL/prepared
    // statements migrations need. See src/lib/db.ts for the runtime connection.
    url: process.env["DIRECT_URL"],
  },
});
